server:
  port: 8080
  servlet:
    context-path: /

spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/hostalive?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true # sql ??? ??
        default_batch_fetch_size: 1000

    show-sql: true  # sql ??
    open-in-view: false